services:
  seasonviewer:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    user: "1000:1000"
    volumes:
      - db:/mnt
    networks:
      - main
    environment:
      - ASPNETCORE_URLS=
      - KESTREL__ENDPOINTS__HTTP1__URL=http://seasonviewer:5020
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
      # garbage collector: workstation
      - DOTNET_gcServer=0

networks:
  main:
    name: main
    external: true

volumes:
  db:
