services:
  seasonbackend:
    build:
      context: .
      dockerfile: Dockerfile.Backend
    restart: always
    user: "1000:1000"
    volumes:
      - db:/mnt
    networks:
      - seasonviewer
      - seleniumminer
    environment:
      - ASPNETCORE_URLS=
      - KESTREL__ENDPOINTS__HTTP2__URL=http://seasonbackend:5021

  seasonviewer:
    build:
      context: .
      dockerfile: Dockerfile.Frontend
    restart: always
    networks:
      - seasonviewer
    environment:
      - ASPNETCORE_URLS=
      - KESTREL__ENDPOINTS__HTTP1__URL=http://seasonviewer:5020
      - BackendUrl=http://seasonbackend:5021

networks:
  seasonviewer:
    name: seasonviewer
  seleniumminer:
    name: seleniumminer
    external: true

volumes:
  db:
