//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeasonTests.Backend.Miner {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeasonTests.Backend.Miner.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;pageSource&quot;:&quot;&lt;html&gt;&lt;!-- sp:feature:head-start --&gt;&lt;head&gt;&lt;script async=\&quot;\&quot; src=\&quot;https://images-eu.ssl-images-amazon.com/images/I/31BVuidgT8L.js\&quot; crossorigin=\&quot;anonymous\&quot;&gt;&lt;\/script&gt;&lt;script&gt;var aPageStart = (new Date()).getTime();&lt;\/script&gt;&lt;meta charset=\&quot;utf-8\&quot;&gt;\n&lt;script type=\&quot;text/javascript\&quot;&gt;var ue_t0=ue_t0||+new Date();&lt;\/script&gt;&lt;!-- sp:feature:cs-optimization --&gt;\n&lt;meta http-equiv=\&quot;x-dns-prefetch-control\&quot; content=\&quot;on\&quot;&gt;&lt;link rel=\&quot;dns-prefetch\&quot; href=\&quot;https://images-eu.ssl-images-amazon.com\&quot;&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string amazon_search {
            get {
                return ResourceManager.GetString("amazon_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Id&quot;:&quot;B07ZHQ34WW&quot;,&quot;Name&quot;:&quot;PSYCHO-PASS 3&quot;,&quot;HosterType&quot;:1},{&quot;Id&quot;:&quot;B0115DA7QM&quot;,&quot;Name&quot;:&quot;Homeland - Staffel 4 [dt./OV]&quot;,&quot;HosterType&quot;:1},{&quot;Id&quot;:&quot;B01671KGTK&quot;,&quot;Name&quot;:&quot;Hand of God - Staffel 1 [dt./OV]&quot;,&quot;HosterType&quot;:1},{&quot;Id&quot;:&quot;B01M2ZKU3I&quot;,&quot;Name&quot;:&quot;Highschool of the Dead [dt./OV]&quot;,&quot;HosterType&quot;:1},{&quot;Id&quot;:&quot;B00NP9UQG6&quot;,&quot;Name&quot;:&quot;Was nicht passt wird passend gemacht&quot;,&quot;HosterType&quot;:1},{&quot;Id&quot;:&quot;B01K5YXG0Q&quot;,&quot;Name&quot;:&quot;Psych - Staffel 1&quot;,&quot;HosterType&quot;:1},{&quot;Id&quot;:&quot;B06WVJ9FZN&quot;,&quot;Name&quot;:&quot;Hand of God - Staffel 2 [dt./OV]&quot;,&quot;HosterType&quot;:1},{&quot;Id&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string amazon_search_expected {
            get {
                return ResourceManager.GetString("amazon_search_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;pageSource&quot;:&quot;&lt;html&gt;&lt;head&gt;    \n&lt;link rel=\&quot;preconnect\&quot; href=\&quot;//fonts.gstatic.com/\&quot; crossorigin=\&quot;anonymous\&quot;&gt;\n&lt;link rel=\&quot;preconnect\&quot; href=\&quot;//fonts.googleapis.com/\&quot; crossorigin=\&quot;anonymous\&quot;&gt;\n&lt;link rel=\&quot;preconnect\&quot; href=\&quot;//tags-cdn.deployads.com/\&quot; crossorigin=\&quot;anonymous\&quot;&gt;\n&lt;link rel=\&quot;preconnect\&quot; href=\&quot;//www.googletagservices.com/\&quot; crossorigin=\&quot;anonymous\&quot;&gt;\n&lt;link rel=\&quot;preconnect\&quot; href=\&quot;//www.googletagmanager.com/\&quot; crossorigin=\&quot;anonymous\&quot;&gt;\n&lt;link rel=\&quot;preconnect\&quot; href=\&quot;//apis.go [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mal_season {
            get {
                return ResourceManager.GetString("mal_season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Id&quot;:0,&quot;Season&quot;:&quot;a47c7f3a-9f7c-41a6-aa30-f1cf9255c5bb&quot;,&quot;Mal&quot;:{&quot;Id&quot;:&quot;38408&quot;,&quot;Name&quot;:&quot;Boku no Hero Academia 4th Season&quot;,&quot;ImageUrl&quot;:&quot;https://cdn.myanimelist.net/r/167x242/images/anime/1315/102961.webp?s=44e2b5e3c48f907284dd189f498cc462&quot;,&quot;MemberCount&quot;:375565,&quot;Score&quot;:826}},{&quot;Id&quot;:0,&quot;Season&quot;:&quot;a47c7f3a-9f7c-41a6-aa30-f1cf9255c5bb&quot;,&quot;Mal&quot;:{&quot;Id&quot;:&quot;39597&quot;,&quot;Name&quot;:&quot;Sword Art Online: Alicization - War of Underworld&quot;,&quot;ImageUrl&quot;:&quot;https://cdn.myanimelist.net/r/167x242/images/anime/1630/103417.webp?s=986f996c398866a677f59641f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mal_season_expected {
            get {
                return ResourceManager.GetString("mal_season_expected", resourceCulture);
            }
        }
    }
}
