services:
  seasonviewer:
    build:
      context: .
    volumes:
      - ../..:/workspaces:cached
      - ../mnt:/mnt
    command: sleep infinity
    networks:
      - main

networks:
  main:
    name: main
    external: true
